name: slim ci

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  actions: read
  pull-requests: write


jobs:
  slim-ci:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: "${{ secrets.SNOWFLAKE_ACCOUNT }}"
      DBT_USER: "${{ secrets.DBT_USER }}"
      SNOWFLAKE_PRIVATE_KEY: "${{ secrets.SNOWFLAKE_PRIVATE_KEY}}"
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: "${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}"
    steps:
      - uses: actions/checkout@v4
      - name: Run CI
        run: |
          echo "Running CI tasks..."
          # Add your CI commands here, for example:
          # npm install
          # npm test
